### PR TITLE
Added Windows support

### PR DESCRIPTION
**Pull request by mbwilding**
Hopefully you don't mind me fixing up some things.

Remove `awk` and `sh` dependencies and removed the need for the separator/delimiter.

Tested on Windows and Linux.

### CODE REVIEW

**Comment by mbwilding** [comment]
Just noticed I have a bug with the path, let me fix it.

**Comment by mbwilding** [comment]
Should be all good now :)

**Comment by mbwilding** [comment]
Fixing another issue LOL two secs.

**Comment by isak102** [comment]
Thanks for the PR! Looks promising, but the highligting of the date and the commit hash does not work anymore, if you could fix that it would be great and then I can merge

**Comment by isak102** [comment]
Thanks for the PR!!

**Pull request merged**
